services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - nginx_default
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nginx_default


  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/sql:/var/lib/mysql
    networks:
      - nginx_default


volumes:
  postgres_data:
  mysql_data:

networks:
  nginx_default:
    external: true

