services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    user: "1000:1000"
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Lisbon
      - PORT=5055 #optional
    ports:
      - 5655:5055
    volumes:
      - ./seerr_conf:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  
  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: SuggestArr
    restart: always
    ports:
      - "${SUGGESTARR_PORT:-5654}:${SUGGESTARR_PORT:-5654}"
    volumes:
      - ./config_files:/app/config/config_files
    environment:
      # Optional: Only needed if something goes wrong and you need to inspect deeper
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Optional: Customize the port (defaults to 5000 if not set)
      - SUGGESTARR_PORT=${SUGGESTARR_PORT:-5654}


  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./radarr:/config
      - /mnt/#NAS/#Media/Movies:/movies #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=6882
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/appdata:/config
      - /mnt/#NAS/#Media/Downloads:/downloads #optional
    ports:
      - 6882:6882
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
