ALLOW_REGISTRATION: false
API_RETRIES: 3
API_TIMEOUT: 30
CACHE_TTL: 24
CRON_TIMES: daily
DB_CONNECTION_TIMEOUT: '30'
DB_MAX_CONNECTIONS: '10'
DB_MAX_IDLE_TIME: '300'
DB_MAX_LIFETIME: '3600'
DB_MIN_CONNECTIONS: '2'
DB_RETRY_ATTEMPTS: '3'
DB_RETRY_DELAY: '1.0'
DB_TYPE: sqlite
ENABLE_ADVANCED_ALGORITHM: false
ENABLE_API_CACHING: true
ENABLE_BETA_FEATURES: false
ENABLE_DEBUG_MODE: false
ENABLE_PERFORMANCE_MONITORING: false
ENABLE_SOCIAL_FEATURES: false
ENABLE_STATIC_BACKGROUND: false
ENABLE_VISUAL_EFFECTS: true
EXCLUDE_DOWNLOADED: true
EXCLUDE_REQUESTED: true
FILTER_GENRES_EXCLUDE: []
FILTER_INCLUDE_NO_RATING: true
FILTER_INCLUDE_TVOD: false
FILTER_RATING_SOURCE: tmdb
FILTER_STREAMING_SERVICES: []
HONOR_JELLYSEER_DISCOVERY: false
JELLYFIN_API_URL: http://10.13.13.5:8096
JELLYFIN_LIBRARIES:
- id: f137a2dd21bbc1b99aa5c0f6bf02a805
  is_anime: false
  name: Movies
JELLYFIN_TOKEN: 0930d66ba0c54dceb50e87f636ca2bdb
LLM_MODEL: gpt-4o-mini
LOG_LEVEL: INFO
MAX_CACHE_SIZE: 100
MAX_CONTENT_CHECKS: '10'
MAX_SIMILAR_MOVIE: '5'
MAX_SIMILAR_TV: '2'
PLEX_CLIENT_ID: 992224a7-4207-4a1d-9702-0fe0f7f86686
PLEX_LIBRARIES: []
SEARCH_SIZE: '20'
SEER_ANIME_PROFILE_CONFIG: {}
SEER_API_URL: http://10.13.13.5:5655
SEER_REQUEST_DELAY: 2
SEER_TOKEN: MTc3MzM5NzgzODYyNzM0NzA0MjM1LTBlNjgtNDFhYy05OGFkLTFmYTJkMTVmNDg5Yg==
SELECTED_SERVICE: jellyfin
SELECTED_USERS:
- id: 3b3025e279c84e96ac03eb5036010d29
  name: rcosta13
SETUP_COMPLETED: true
STATIC_BACKGROUND_COLOR: '#2E3440'
TMDB_API_KEY: ed7415aa4850f01e2c95e926ad1d6bb8
